### ISSUE TITLE
Best way to implement Datagrid Multiselect?

### ISSUE THREAD

**Issue by eu-genes** [elmish/Elmish.WPF#381] opened 2021-04-02 07:24 UTC
I need multiselect for my datagrid, but `subModelSelectedItem` works only for single select.

**Comment by TysonMN** [comment] 2021-04-02 12:43
Yes, I am aware of this missing feature.  It is on the list of things to do but is not top priority at the moment.  One reason for that is workarounds exist.  This issue is a duplicate of #188.  See especially https://github.com/elmish/Elmish.WPF/issues/188#issuecomment-557865424 and https://github.com/elmish/Elmish.WPF/issues/188#issuecomment-557880106.

**Closed by TysonMN** 2021-04-02 12:43 UTC
