### ISSUE TITLE
How to close the console window automatically when the WPF application closes?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#352] opened 2021-02-23 05:39 UTC
I'm sure this is somewhere, but I can't seem to find it.

I have an F# project (written in Visual Studio) that executes from a console application to start WPF:

[<EntryPoint; STAThread>]
   let main argv =
     Program.mkProgramWpf init update bindings
     |> Program.runWindowWithConfig
        { ElmConfig.Default with LogConsole = false }      
        (FrontOffice())

When the wpf application closes, how can I automatically close the console window as well?

Thanks :)

(Currently the console window remains open with: "Press Any Key").

**Comment by TysonMN** [comment] 2021-02-23 05:51
If you check, you will find that every sample has your desired behavior.  Your application does not have your desired behavior because you have some computation still executing.  This has nothing to do with WPF.  However, if you share a GitHub repo containing executable code that reproduces this behavior, then I can help you fix it _properly_.

A hack solution would be something like subscribing to [`Window.Closed`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.closed) and executing something like [`System.Environement.Exit(0)`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit#System_Environment_Exit_System_Int32_).

**Comment by TysonMN** [comment] 2021-02-23 05:55
> Currently the console window remains open with: "Press Any Key"

Wait...are you talking about the [this feature in Visual Studio where the console doesn't close right away](https://stackoverflow.com/questions/1775865/preventing-console-window-from-closing-on-visual-studio-c-c-console-applicatio/54084067#54084067)?

In addition to toggling that setting, you can easily test this by directly executing your exe instead of executing through Visual Studio.  Does the console window also stay open after closing the window in that case?

**Comment by TysonMN** [comment] 2021-03-08 15:13
If you are still having problem, please share a screenshot or reproduction.

**Closed by TysonMN** 2021-03-08 15:13 UTC
