### ISSUE TITLE
when binding a data context to an sub element, the visibility binding could not be found

### ISSUE THREAD

**Issue by nathans1309** [elmish/Elmish.WPF#435] opened 2021-09-26 16:26 UTC
Here is an example of what I was trying to do in Parent.xaml
```
<Grid>
...
<ChildComponent Grid.Row="0" Grid.Column="2" DataContext="{Binding ChildProperty}" Visibility="{Binding ShowChildRecord}" />
...
</Grid>
```
Then I set the parent Bindings for `ChildProperty` and `ShowChildRecord` in the same place as such

```
...
"ChildProperty" |> Binding.subModel (id, snd, id, childBindings)
"ShowChildRecord" |> Binding.oneWay (fun m -> true)
...
```

I kept getting an error that the binding for `ShowChildRecord` could not be found. 
I was able to resolve the issue by moving the `ShowChildRecord` binding to the child component's bindings even though I feel that the visibility of this child component is a responsibility of the parent component.

My assumption is that using DataContext in the parent xaml with `Binding.subModel` in the parent bindings will treat all of the child component xaml properties (such as Visibility) as child bindings. I found that a bit confusing that a binding which was visible in the parent xaml could be matched against a child binding

Where I need some guidance is to know whether this is by design or an oversight to how I'm utilizing the framework.
Thanks

**Comment by TysonMN** [comment] 2021-09-26 16:42
> Where I need some guidance is to know whether this is by design or an oversight to how I'm utilizing the framework.

I think this is by design by Microsoft in WPF.  This has nothing to do with Elmish.WPF.

This issue is a duplicate of [this SO question](https://stackoverflow.com/questions/3550010/bind-visibility-to-different-source-than-datacontext/3551714) from 11 years ago.  Both solutions there show ways to use relative bindings to achieve the desired result.  Think the relative binding syntax is verbose and a bit confusing.  Instead, I prefer adding an extra layer into the visual tree just to handle visibility.

```xaml
<Grid>
  ...
  <Grid Visibility="{Binding ShowChildRecord}">
    <ChildComponent Grid.Row="0" Grid.Column="2" DataContext="{Binding ChildProperty}"/>
  </Grid>
  ...
</Grid>
```

**Closed by TysonMN** 2021-09-26 16:42 UTC
