### ISSUE TITLE
DevOps: .paket/Paket.Restore.targets auto modified

### ISSUE THREAD

**Issue by bender2k14** [elmish/Elmish.WPF#100] opened 2019-08-21 17:42 UTC
When I have `Elmish.WPF.sln` open in Visual Studio, the file `.paket/Paket.Restore.targets` is automatically mutated.  I am aware of the F# build automation tool [FAKE](https://fake.build/) but have yet to use it myself.  With my limited knowledge, it is unclear to me (and [others](https://github.com/fsprojects/Paket/issues/2840)) whether `Paket.Restore.targets` files should ignore or commited.

Does someone here know what should be done?

Once a decision is made, I can make a PR for the change.

**Comment by cmeeren** [comment] 2019-08-21 17:50
I think it needs to be present for restore in VS to work (if not using FAKE), since the project files reference those targets. If it's updated (which it often is), I usually just commit it.

In any case, I think it can be improved by pinning the paket version in `paket.dependencies`, which should probably be done anyway to ensure reproducible builds (automatic paket upgrades have broken builds before in some of my projects). Hopefully fixed with 7968ad0d915fb7401d340e5c9814b2190c31e394.

**Closed by cmeeren** 2019-08-21 17:50 UTC

**Comment by bender2k14** [comment] 2019-08-21 19:27
Indeed, that files is no longer being modified for me.  Thanks :)
