### ISSUE TITLE
How to keep popup open?

### ISSUE THREAD

**Issue by awaynemd** [elmish/Elmish.WPF#299] opened 2020-11-18 22:38 UTC
(Newbie question :) )

I am having difficulty getting my wpf popup to stay open with Elmish.wpf. 

Actually, I have several issues:
♦ Issue with Popup staying open or reopen
♦ How to set a property from xaml? (i.e isOpen). WPF defines IsOpen as {get; set:} directly from the XAML code. How can I wire IsOpen from the XAML code to directly set this property in my Elmish Model?
♦ How can I match on an empty string? 

Thanks for any help or suggestions.

Full Code found at: https://github.com/awaynemd/Popup

**Comment by TysonMN** [comment] 2020-11-19 02:46
Duplicate of #298

**Closed by TysonMN** 2020-11-19 02:46 UTC
